### ISSUE TITLE
GulpJS configuration

### ISSUE THREAD

**Issue by pudly** [toitoi-co/toitoi-cms#1]
Baseline gulpJS configuration for the project
- SASS
- Anything and everything that makes sense for ReactJS + Flux
- Webpack
- PostCSS
- LiveReload

**Comment by joepie91** [comment]
Additional comments:
- I've left some code structure comments in the sample React component.
- You didn't specify the needed PostCSS plugins, so I've only added `autoprefixer` - instructions on adding more plugins are in the `gulpfile.js`.
- Adding a Flux implementation should not require any additions to the build stack, at least in theory - since it's set up with Webpack, anything CommonJS-based can be bundled in automatically.
- Component styles should always go into their corresponding SCSS files. The `src/scss/` folder only exists for non-component-specific, page-wide styles - and may be useful for things like theme overrides at a later point.
